/* The following code was generated by JFlex 1.7.0 */

package ar.edu.itba.relif.parser;
import java.io.*;
import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.Location;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>grammar/lexer.flex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\4\22\0\1\3\1\30\4\0\1\24"+
    "\4\0\1\20\1\16\1\21\1\22\1\0\12\1\2\0\1\36\1\17"+
    "\1\34\2\0\32\2\6\0\1\32\2\2\1\7\1\10\1\37\2\2"+
    "\1\6\2\2\1\15\1\27\1\11\1\25\1\35\1\2\1\14\1\26"+
    "\1\31\1\12\1\13\4\2\1\0\1\33\1\0\1\23\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff91\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\4\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\2\1\1\12\1\1\2\0\1\1"+
    "\1\13\2\1\1\14\3\1\1\15\1\16\1\17\2\1"+
    "\1\17\1\0\2\1\1\20\1\12\1\1\1\21\1\22"+
    "\1\1\1\16\1\20\1\23\1\1\1\24\1\25\2\1"+
    "\1\15";

  private static int [] zzUnpackAction() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\40\0\100\0\140\0\200\0\240\0\300\0\340"+
    "\0\100\0\u0100\0\100\0\100\0\100\0\100\0\u0120\0\u0140"+
    "\0\u0160\0\100\0\u0180\0\u01a0\0\u01c0\0\u01e0\0\40\0\u0200"+
    "\0\u0220\0\u0240\0\u0260\0\u0280\0\u02a0\0\100\0\100\0\40"+
    "\0\u02c0\0\u02e0\0\100\0\u0300\0\u0320\0\u0340\0\40\0\40"+
    "\0\u0360\0\40\0\40\0\u0380\0\40\0\100\0\40\0\u03a0"+
    "\0\40\0\40\0\u03c0\0\u03e0\0\40";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\0\1\2\1\3\1\4\1\3\1\5\2\2\1\6"+
    "\1\7\1\2\1\10\1\2\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\2\1\22\1\2"+
    "\1\23\1\24\1\0\1\2\1\25\1\2\1\0\2\2"+
    "\3\0\10\2\7\0\3\2\1\0\2\2\2\0\1\2"+
    "\1\0\1\2\45\0\1\3\33\0\2\2\3\0\1\2"+
    "\1\26\1\2\1\27\4\2\7\0\2\2\1\30\1\0"+
    "\2\2\2\0\1\2\1\0\1\31\1\0\2\2\3\0"+
    "\10\2\7\0\1\32\2\2\1\0\2\2\2\0\1\2"+
    "\1\0\1\2\1\0\2\2\3\0\3\2\1\33\4\2"+
    "\7\0\3\2\1\0\2\2\2\0\1\2\1\0\1\2"+
    "\1\0\2\2\3\0\2\2\1\34\1\2\1\35\3\2"+
    "\7\0\3\2\1\0\2\2\2\0\1\2\1\0\1\2"+
    "\34\0\1\36\27\0\1\37\14\0\2\2\3\0\6\2"+
    "\1\40\1\2\7\0\3\2\1\0\2\2\2\0\1\2"+
    "\1\0\1\2\1\0\2\2\3\0\10\2\7\0\1\41"+
    "\2\2\1\0\2\2\2\0\1\2\1\0\1\2\1\0"+
    "\2\2\3\0\3\2\1\42\4\2\7\0\3\2\1\0"+
    "\2\2\2\0\1\2\1\0\1\2\33\0\1\43\23\0"+
    "\1\44\21\0\2\2\3\0\2\2\1\45\5\2\7\0"+
    "\3\2\1\0\2\2\2\0\1\2\1\0\1\2\1\0"+
    "\2\2\3\0\10\2\7\0\3\2\1\0\2\2\2\0"+
    "\1\46\1\0\1\2\1\0\2\2\3\0\10\2\7\0"+
    "\3\2\1\0\2\2\2\0\1\2\1\0\1\47\1\0"+
    "\2\2\3\0\10\2\7\0\3\2\1\0\1\50\1\2"+
    "\2\0\1\2\1\0\1\2\1\0\2\2\3\0\1\51"+
    "\7\2\7\0\3\2\1\0\2\2\2\0\1\2\1\0"+
    "\1\2\1\0\2\2\3\0\7\2\1\52\7\0\3\2"+
    "\1\0\2\2\2\0\1\2\1\0\1\2\1\0\2\2"+
    "\3\0\3\2\1\53\4\2\7\0\3\2\1\0\2\2"+
    "\2\0\1\2\1\0\1\2\1\0\2\2\3\0\10\2"+
    "\7\0\2\2\1\54\1\0\2\2\2\0\1\2\1\0"+
    "\1\2\1\0\2\2\3\0\1\2\1\55\6\2\7\0"+
    "\3\2\1\0\2\2\2\0\1\2\1\0\1\2\34\0"+
    "\1\56\4\0\2\2\3\0\3\2\1\57\4\2\7\0"+
    "\3\2\1\0\2\2\2\0\1\2\1\0\1\2\1\0"+
    "\2\2\3\0\7\2\1\60\7\0\3\2\1\0\2\2"+
    "\2\0\1\2\1\0\1\2\1\0\2\2\3\0\5\2"+
    "\1\61\2\2\7\0\3\2\1\0\2\2\2\0\1\2"+
    "\1\0\1\2\1\0\2\2\3\0\2\2\1\62\5\2"+
    "\7\0\3\2\1\0\2\2\2\0\1\2\1\0\1\2"+
    "\1\0\2\2\3\0\1\63\7\2\7\0\3\2\1\0"+
    "\2\2\2\0\1\2\1\0\1\2\1\0\2\2\3\0"+
    "\2\2\1\64\5\2\7\0\3\2\1\0\2\2\2\0"+
    "\1\2\1\0\1\2\1\0\2\2\3\0\10\2\7\0"+
    "\1\2\1\65\1\2\1\0\2\2\2\0\1\2\1\0"+
    "\1\2";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\11\5\1\1\11\1\1\4\11\3\1"+
    "\1\11\1\1\2\0\10\1\2\11\3\1\1\11\1\0"+
    "\11\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[53];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	public Scanner(java.io.Reader r, ComplexSymbolFactory sf){
		this(r);
		this.sf=sf;
	}
	public Symbol symbol(String plaintext,int code){
	    return sf.newSymbol(plaintext, code, new Location("",yyline+1, yycolumn +1,yychar), new Location("",yyline+1,yycolumn+yylength(),yychar));
	}
	public Symbol symbol(String plaintext,int code, String value){
	    return sf.newSymbol(plaintext,code,new Location("",yyline+1, yycolumn +1,yychar), new Location("",yyline+1,yycolumn+yylength(),yychar), value);
	}
	private ComplexSymbolFactory sf;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return sf.newSymbol("EOF", sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { String s = yytext(); return symbol(s, sym.IDENTIFIER, s);
            } 
            // fall through
          case 22: break;
          case 2: 
            { 
            } 
            // fall through
          case 23: break;
          case 3: 
            { return symbol(yytext(), sym.COMMA);
            } 
            // fall through
          case 24: break;
          case 4: 
            { return symbol(yytext(), sym.EQUALS);
            } 
            // fall through
          case 25: break;
          case 5: 
            { return symbol(yytext(), sym.PLUS);
            } 
            // fall through
          case 26: break;
          case 6: 
            { return symbol(yytext(), sym.MINUS);
            } 
            // fall through
          case 27: break;
          case 7: 
            { return symbol(yytext(), sym.COMPOSE);
            } 
            // fall through
          case 28: break;
          case 8: 
            { return symbol(yytext(), sym.CONVERSE);
            } 
            // fall through
          case 29: break;
          case 9: 
            { return symbol(yytext(), sym.INTERSECTION);
            } 
            // fall through
          case 30: break;
          case 10: 
            { return symbol(yytext(), sym.NOT);
            } 
            // fall through
          case 31: break;
          case 11: 
            { return symbol(yytext(), sym.IN);
            } 
            // fall through
          case 32: break;
          case 12: 
            { return symbol(yytext(), sym.NO);
            } 
            // fall through
          case 33: break;
          case 13: 
            { return symbol(yytext(), sym.IMPLIES);
            } 
            // fall through
          case 34: break;
          case 14: 
            { return symbol(yytext(), sym.AND);
            } 
            // fall through
          case 35: break;
          case 15: 
            { return symbol(yytext(), sym.OR);
            } 
            // fall through
          case 36: break;
          case 16: 
            { return symbol(yytext(), sym.IFF);
            } 
            // fall through
          case 37: break;
          case 17: 
            { return symbol(yytext(), sym.REL);
            } 
            // fall through
          case 38: break;
          case 18: 
            { return symbol(yytext(), sym.RUN);
            } 
            // fall through
          case 39: break;
          case 19: 
            { return symbol(yytext(), sym.IDEN);
            } 
            // fall through
          case 40: break;
          case 20: 
            { return symbol(yytext(), sym.UNIV);
            } 
            // fall through
          case 41: break;
          case 21: 
            { return symbol(yytext(), sym.SOME);
            } 
            // fall through
          case 42: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
