
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ar.edu.itba.relif.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SOME = 13;
  public static final int LBRACKET = 33;
  public static final int EQUALS = 4;
  public static final int UNIV = 15;
  public static final int CONVERSE = 8;
  public static final int REL = 2;
  public static final int FOR = 26;
  public static final int MINUS = 6;
  public static final int CLOSEPAREN = 24;
  public static final int NOT = 18;
  public static final int AND = 19;
  public static final int OPENPAREN = 23;
  public static final int ASYMMETRIC = 29;
  public static final int IN = 11;
  public static final int OR = 20;
  public static final int COMMA = 10;
  public static final int ATOM = 3;
  public static final int IMPLIES = 21;
  public static final int PLUS = 5;
  public static final int EOF = 0;
  public static final int RBRACKET = 34;
  public static final int error = 1;
  public static final int INTERSECTION = 9;
  public static final int NEWLINE = 25;
  public static final int CHECK = 17;
  public static final int NUMBER = 36;
  public static final int NO = 12;
  public static final int COMPOSE = 7;
  public static final int BUT = 31;
  public static final int IDEN = 14;
  public static final int DEFAULT = 30;
  public static final int EXACTLY = 32;
  public static final int IDENTITY = 28;
  public static final int SYMMETRIC = 27;
  public static final int RUN = 16;
  public static final int IFF = 22;
  public static final int IDENTIFIER = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "REL",
  "ATOM",
  "EQUALS",
  "PLUS",
  "MINUS",
  "COMPOSE",
  "CONVERSE",
  "INTERSECTION",
  "COMMA",
  "IN",
  "NO",
  "SOME",
  "IDEN",
  "UNIV",
  "RUN",
  "CHECK",
  "NOT",
  "AND",
  "OR",
  "IMPLIES",
  "IFF",
  "OPENPAREN",
  "CLOSEPAREN",
  "NEWLINE",
  "FOR",
  "SYMMETRIC",
  "IDENTITY",
  "ASYMMETRIC",
  "DEFAULT",
  "BUT",
  "EXACTLY",
  "LBRACKET",
  "RBRACKET",
  "IDENTIFIER",
  "NUMBER"
  };
}

