
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ar.edu.itba.relif.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 17;
  public static final int PLUS = 4;
  public static final int OR = 18;
  public static final int IN = 10;
  public static final int REL = 2;
  public static final int NOT = 16;
  public static final int CONVERSE = 7;
  public static final int IDENTIFIER = 21;
  public static final int IDEN = 13;
  public static final int IMPLIES = 19;
  public static final int EQUALS = 3;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int RUN = 15;
  public static final int COMPOSE = 6;
  public static final int MINUS = 5;
  public static final int IFF = 20;
  public static final int error = 1;
  public static final int SOME = 12;
  public static final int UNIV = 14;
  public static final int INTERSECTION = 8;
  public static final int NO = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "REL",
  "EQUALS",
  "PLUS",
  "MINUS",
  "COMPOSE",
  "CONVERSE",
  "INTERSECTION",
  "COMMA",
  "IN",
  "NO",
  "SOME",
  "IDEN",
  "UNIV",
  "RUN",
  "NOT",
  "AND",
  "OR",
  "IMPLIES",
  "IFF",
  "IDENTIFIER"
  };
}

